<a href="https://colab.research.google.com/github/Rohit3435/Python-Practice/blob/main/Python_practice_Data_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hi")

hi

**1.Create a dictionary called company_dict with this data.<br>
id company<br>
1 Alphabet<br>
2 Google<br>
3 MySql<br>**

In [ ]:
py_dict={'id':[1,2,3],
         'company': ['Alphabet','Google','MySql']}

In [ ]:
py_dict

{'id': [1, 2, 3], 'company': ['Alphabet', 'Google', 'MySql']}

**2. Change the company name MySQL to MariaDb in the dict**

In [ ]:
py_dict["company"][2]='MariaDb';
py_dict

{'id': [1, 2, 3], 'company': ['Alphabet', 'Google', 'MariaDb']}

**. 3.Create a pandas dataframe from the dict.**

In [ ]:
import pandas as pd
df=pd.DataFrame(py_dict)
df

   id   company
0   1  Alphabet
1   2    Google
2   3   MariaDb

**4.List the Top 1 customer of the dataframe**

In [ ]:
df.head(1)

   id   company
0   1  Alphabet


**5. Order the dataset by company name**
```

In [ ]:
df.sort_values('company')

   id   company
0   1  Alphabet
1   2    Google
2   3   MariaDb

 6. Create a region dataframe based on this data

| id | region |
|----|--------|
| 1  | AMER   |
| 2  | AMER   |
| 3  | EMEA   |

Merge it with the company dataframe based on **ID**.

merge it with company dataframe based on ID.

In [ ]:
region={'id':[1,2,3,4],
        'region':['AMER','AMER','EMEA','INDIA']}
region_df=pd.DataFrame(region)
merged_df=df.merge(region_df,how='left',on='id')
merged_df

   id   company region
0   1  Alphabet   AMER
1   2    Google   AMER
2   3   MariaDb   EMEA

## **7.1 Figure out the error in the code below**
7.2 Write a single line code to do the same what this function is doing**

# New Sectiondef output_all_odd(x_list):<br>
all_odd_numbers = range(1,x_list.max()+1,2) <br>
for i in x_list:<br>
y_list = []<br>
if i in all_odd_numbers:<br>
y_list.append(i)<br>
return(y_list)<br>

**below needs**

x_list=[1,2,3,4,5,7,9]**bold text**

output_all_odd(x_list)

[1, 3, 5, 7, 9]

In [3]:
def output_all_odd(x_list):
  all_odd_numbers = range(1,max(x_list)+1,2)
  y_list = []
  for i in x_list:
    if i in all_odd_numbers:
      y_list.append(i)
  return(y_list)

In [4]:
x_list=[1,2,3,4,5,7,9]

In [5]:
output_all_odd(x_list)

[1, 3, 5, 7, 9]

In [11]:

y_list=[];
for x in x_list:
  if x%2!=0:
    y_list.append(x);
y_list

[1, 3, 5, 7, 9]

**8. Write a Python function that takes a list of IDs and increments each ID by 1 using a for loop. If an ID is not an integer, the function should handle the exception and print an error message. The function should return a list of incremented IDs.**

Example

# Input: [1, 2, 'a', 4]
# Output:
# Error: ID 'a' is not an integer.
# [2, 3, 5]

In [37]:
incremented_IDs=[];
im=[1, 2, 'a', 4];
for i in im:
  if(type(i)==int):
    incremented_IDs.append(i+1);
  else:

    print(i, ' is not an integer')

incremented_IDs

a  is not an integer

[2, 3, 5]

**9. Given a string s, return the longest palindromic substring in s.
Example 1:
Input: s = "babad" Output: "bab" Explanation: "aba" is also a valid answer.

Example 2:
Input: s = "cbbd" Output: "bb"

Constraints: 1 <= s.length <= 1000 s consist of only digits and English letters.

In [31]:
s='zcbbbcd'
max_len=len(s)
longest_palindrome=""
palindrome=[]

for i in range(0,max_len+1):
  # print(i,'value if i')
  for j in range(0,max_len+1):
    # print(j,'value of j')
    # print(s[i:j])
    if s[i:j]==s[i:j][::-1]:
      if s[i:j]!='':
        palindrome.append(s[i:j])

In [32]:
palindrome

['z', 'c', 'cbbbc', 'b', 'bb', 'bbb', 'b', 'bb', 'b', 'c', 'd']

10. Create this list in python using list comprehension. Give a custom input 3 or any other number to generate this list
(1, 1), (2, 1), (2, 2), (3, 1), (3, 2), (3, 3)

In [38]:
n = int(input("Enter the value: "))

result = [(i, j) for i in range(1, n + 1)
                  for j in range(1, i + 1)]

print(result)

TypeError: 'list' object is not callable