<a href="https://colab.research.google.com/github/Rohit3435/Python-Practice/blob/main/Python_practice_Data_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hi")

hi

**1.Create a dictionary called company_dict with this data.<br>
id company<br>
1 Alphabet<br>
2 Google<br>
3 MySql<br>**

In [3]:
py_dict={'id':[1,2,3],
         'company': ['Alphabet','Google','MySql']}

In [4]:
py_dict

{'id': [1, 2, 3], 'company': ['Alphabet', 'Google', 'MySql']}

**2. Change the company name MySQL to MariaDb in the dict**

In [13]:
py_dict["company"][2]='MariaDb';
py_dict

{'id': [1, 2, 3], 'company': ['Alphabet', 'Google', 'MariaDb']}

**. 3.Create a pandas dataframe from the dict.**

In [16]:
import pandas as pd
df=pd.DataFrame(py_dict)
df

   id   company
0   1  Alphabet
1   2    Google
2   3   MariaDb

**4.List the Top 1 customer of the dataframe**

In [17]:
df.head(1)

   id   company
0   1  Alphabet


**5. Order the dataset by company name**
```

In [19]:
df.sort_values('company')

   id   company
0   1  Alphabet
1   2    Google
2   3   MariaDb

 6. Create a region dataframe based on this data

| id | region |
|----|--------|
| 1  | AMER   |
| 2  | AMER   |
| 3  | EMEA   |

Merge it with the company dataframe based on **ID**.

merge it with company dataframe based on ID.

In [23]:
region={'id':[1,2,3,4],
        'region':['AMER','AMER','EMEA','INDIA']}
region_df=pd.DataFrame(region)
merged_df=df.merge(region_df,how='left',on='id')
merged_df

   id   company region
0   1  Alphabet   AMER
1   2    Google   AMER
2   3   MariaDb   EMEA